create table if not exists public.reservations (
  id text primary key,
  buyer_number bigint generated by default as identity unique,
  prize text not null default 'Premio Principal',
  ticket_numbers jsonb not null default '[]'::jsonb,
  name text not null,
  last_name text not null,
  state text not null,
  phone text not null,
  status text not null default 'en_revision'
    check (status in ('en_revision', 'pendiente', 'pagado', 'cancelado', 'expirado')),
  receipt_url text not null,
  receipt_name text,
  created_at timestamptz not null default now(),
  sent_at timestamptz not null default now(),
  paid_at timestamptz,
  status_updated_at timestamptz,
  held_until timestamptz
);

create index if not exists reservations_phone_idx on public.reservations (phone);
create index if not exists reservations_status_idx on public.reservations (status);
create index if not exists reservations_created_at_idx on public.reservations (created_at desc);

alter table public.reservations enable row level security;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'receipts',
  'receipts',
  true,
  12582912,
  array['image/png', 'image/jpeg', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
